version: '3'

services:
  event-bus:
    build: ./database/event-bus
    ports:
      - "6380:6379"
    container_name: event-bus
    networks:
      - peerprep

  collaboration-cache:
    build: ./database/collaboration-cache
    ports:
      - "6379:6379"
    container_name: collaboration-cache
    networks:
      - peerprep

  user-service:
    container_name: user-service
    build: 
      context: ./backend/user-service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5005:5005"
    restart: always
    networks:
      - peerprep

  question-service:
    container_name: question-service
    build:
      context: ./backend/question-service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5100:5100"
    restart: always
    networks:
      - peerprep

  auth-service:
    container_name: auth-service
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5050:5050"
    restart: always
    networks:
      - peerprep
    depends_on:
      - user-service

  matching-service:
    container_name: matching-service
    build: 
      context: ./backend/matching-service
      dockerfile: Dockerfile
      args:
        EVENT_BUS_CONTAINER_NAME: event-bus
    env_file:
      - ./.env
    ports:
      - "5200:5200"
    restart: always
    networks:
      - peerprep

  collaboration-service:
    container_name: collaboration-service
    build: 
      context: ./backend/collaboration-service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5300:5300"
    restart: always
    networks:
      - peerprep

  history-service:
    container_name: history-service
    build:
      context: ./backend/history-service
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "5400:5400"
    restart: always
    networks:
      - peerprep

  frontend:
    depends_on:
      - auth-service
      - user-service
      - matching-service
      - collaboration-service
      - history-service
      - question-service
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"
    env_file:
      - ./.env
    restart: always
    networks:
      - peerprep
    
networks:
  peerprep:
    driver: bridge