services:
  event-bus:
    build: ./event-bus
    ports:
      - "6380:6380"
    networks:
      - peerprep
  collaboration-cache:
    build: ./collaboration-cache
    ports:
      - "6379:6379"
    networks:
      - peerprep
  collaboration-service:
    build: ./collaboration-service
    ports:
      - "5300:5300"
    args:
      - EVENT_BUS_CONTAINER_NAME=event-bus
      - COLLABORATION_CACHE_CONTAINER_NAME=collaboration-cache
    networks:
      - peerprep
  matching-service:
    build: ./matching-service
    ports:
      - "5200:5200"
    args:
      - EVENT_BUS_CONTAINER_NAME=event-bus
    networks:
      - peerprep

networks:
  peerprep:
    driver: bridge