export enum SERVICE {
  USER = "user",
  QUESTION = "questions",
}

export enum HTTP_METHODS {
  GET = "GET",
  POST = "POST",
  PUT = "PUT",
  DELETE = "DELETE",
}

export enum Status {
  ACTIVE = "active",
  INACTIVE = "inactive",
}

export enum Role {
  ADMIN = "admin",
  USER = "user",
}

export enum COMPLEXITY {
  EASY = "EASY",
  MEDIUM = "MEDIUM",
  HARD = "HARD",
}

export enum LANGUAGE {
  PYTHON = "PYTHON",
  JAVA = "JAVA",
  CPP = "C++",
  JAVASCRIPT = "JAVASCRIPT",
}

export enum TOPIC {
  ARRAY = "ARRAY",
  BACKTRACKING = "BACKTRACKING",
  BFS = "BREADTH-FIRST SEARCH",
  BINARYSEARCH = "BINARY SEARCH",
  DFS = "DEPTH-FIRST SEARCH",
  DIVIDECONQUER = "DIVIDE AND CONQUER",
  DP = "DYNAMIC PROGRAMMING",
  LINKEDLIST = "LINKED LIST",
  GREEDY = "GREEDY",
  HASHTABLE = "HASH TABLE",
  MATRIX = "MATRIX",
  MEMOIZATION = "MEMOIZATION",
  RECURSION = "RECURSION",
  STACK = "STACK",
  STRING = "STRING",
  SORTING = "SORTING",
  TOPOSORT = "TOPOLOGICAL SORT",
  TREE = "TREE",
  TRIE = "TRIE",
  TWOPOINTERS = "TWO POINTERS",
  QUEUE = "QUEUE",
  QUICKSELECT = "QUICKSELECT",
  UNIONFIND = "UNION FIND",
}
