services:
  event-bus:
    build: ./event-bus
    ports:
      - "6380:6380"
    networks:
      - peerprep
  collaboration-cache:
    build: ./collaboration-cache
    ports:
      - "6379:6379"
    networks:
      - peerprep

networks:
  peerprep:
